### PR TITLE
fix params bugs.

### PR DESCRIPTION
**Pull request by vincentjiang**
Hi, I have fixed the params bugs.

### CODE REVIEW

**Comment by linjunpop** [comment]
Can I know why setting the default values?

**Comment by vincentjiang** [comment]
Because when I run rake db:migrate, it have some errors.
image

**Comment by linjunpop** [comment]
Aha, because your ruby is 2.0 and it doesn’t have built-in support for _required_ keyword arguments. But [2.1 does](https://github.com/ruby/ruby/blob/ruby_2_1/NEWS#L16-17).

**Comment by vincentjiang** [comment]
I see, thank you very much. Then I must use my gem that forked from yours.

**Comment by linjunpop** [comment]
I'll see if I can add support for 2.0.

**Comment by linjunpop** [comment]
I gonna merge this and see if I can find a better way to support required arguments on ruby 2.0.

**Comment by vincentjiang** [comment]
Thank you.

**Pull request merged**
